import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="bg-gray-800 text-white p-4 fixed top-0 w-full z-50 shadow">
          <div className="container mx-auto">Header fixo</div>
        </header>

        <main className="flex-1 mt-16 mb-16 container mx-auto px-4">
          {children}
        </main>

        <footer className="bg-gray-900 text-white p-4 fixed bottom-0 w-full z-50 shadow">
          <div className="container mx-auto">Footer fixo</div>
        </footer>
      </body>
    </html>
  );
}
